### ISSUE TITLE
continuous scan with Exposure time < Acquire period

### ISSUE THREAD

**Issue by gianthk** [SESAME-Synchrotron/BEATS_tomoscan#1]
- [x] ORYX FLIR
- [x] PCO edge 5.5 

---
For PCO-edge 5.5:

- Global shutter modes allow Exposure time down to 10 us
- Exposure time is taken for calculation of rot speed in cont. scan
- This leads to miscalculation of rotation speed and scan error: the scan does many turns instead of 180 degrees

**Comment by Mustafa-zubi** [comment]
Real FPS of the being used cameras is now considered to compute the motor speed (not the exposure time). 
Ready for testing for both cameras.... let's test it with beam.

**Comment by gianthk** [comment]
- [X] ORYX FLIR: tested with exp. time 0.0055 s
- [ ] PCO edge 5.5

**Comment by gianthk** [comment]
- [X] PCO: tested and working fine
