### ISSUE TITLE
wrong rot speed calculation

### ISSUE THREAD

**Issue by gianthk** [SESAME-Synchrotron/BEATS_tomoscan#11]
related to #10

**Comment by Mustafa-zubi** [comment]
Response for issues # 9, 10 and 11:
Problem was investigated ... the actual read back of the cam FPS that is used to calculate frame time and motor speed is not updated until the one a) acquire some frames and b) wait some time around 1 second ... on windows camera software this FPS read back is updated automatically (i.e. upon changing exp. time) but this is not the case in the IOC / EPICS driver. 
Im adding control team to this issue @anas-abadi @AbdallaDalleh
