### ISSUE TITLE
synApps sscan with BEATS detector

### ISSUE THREAD

**Issue by userbeats** [SESAME-Synchrotron/BEATS_tomoscan#5]
[synApps sscan](https://epics.anl.gov/bcda/synApps/sscan/sscan.html):

[see Github page](https://github.com/epics-modules/sscan).

- [ ] example on how to use sscan for set of image collection with single axis (multiple axis) motor movement

**Comment by Anasmoh999** [comment]
Since SSCAN has been added into the BEATS dashboard and has been tested initially on slits movements >>> Ready to collect the data (positions & photos) and save them in the predefined location.

**Comment by gianthk** [comment]
seems to work perfectly. hurrah to our DAQ group
